# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20161214_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
