# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20161215_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
